source:
  hosts:
    - "source-cassandra-host1:9042"
    - "source-cassandra-host2:9042"
  keyspace: "source_keyspace"
  username: "source_user"
  password: "source_password"
  tables:
    - name: "table1"
      target_name: "new_table1"  # 可选，如果需要在目标库中使用不同的表名
    - name: "table2"
    - name: "table3"

destination:
  hosts:
    - "dest-scylla-host1:9042"
    - "dest-scylla-host2:9042"
  keyspace: "dest_keyspace"
  username: "dest_user"
  password: "dest_password"

migration:
  batch_size: 1000
  workers: 4
  rate_limit: 5000  # 每秒写入操作数限制
  timeout: 30       # 连接超时时间(秒)
  checkpoint_dir: "./checkpoints"  # 断点文件存储目录
  log_file: "./migration.log"    # 添加日志文件路径
  checkpoint_delay: 30  # 可选，默认60秒
  log_level: "info"  # 可选，日志级别，默认info