source:
  hosts:
    - "localhost:27017"  # MongoDB/MySQL/Cassandra/PostgreSQL 的主机地址
  database: "test_db"    # MySQL/MongoDB/PostgreSQL 的数据库名
  schema: public # PostgreSQL 的 schema，默认public
  keyspace: "test_ks"    # Cassandra 的 keyspace
  username: "root"
  password: "password"
  tables:
    - name: "users"
      target_name: "users_new"  # 可选，指定目标表名
    - name: "orders"
    - name: "products"

destination:
  hosts:
    - "localhost:27018"
  database: "new_db"
  keyspace: "new_ks"
  username: "root"
  password: "password"

migration:
  batch_size: 1000        # 每批处理的记录数
  workers: 4              # 并发工作线程数
  rate_limit: 10000       # 每秒处理的记录数限制
  timeout: 30             # 连接超时时间（秒）
  checkpoint_dir: "./data/checkpoints"  # 断点续传文件保存目录（默认）
  checkpoint_delay: 60    # 断点保存间隔（秒）
  log_file: "./data/logs/migration.log"  # 日志文件路径（默认）
  log_level: "info"
  progress_interval: 5    # 进度报告间隔时间（秒）