source:
  hosts:
    - "localhost:27017"  # MongoDB/MySQL/Cassandra 的主机地址
  database: "test_db"    # MySQL/MongoDB 的数据库名
  keyspace: "test_ks"    # Cassandra 的 keyspace
  username: "root"
  password: "password"
  tables:
    - name: "users"
      target_name: "users_new"  # 可选，指定目标表名
    - name: "orders"
    - name: "products"

destination:
  hosts:
    - "localhost:27018"
  database: "new_db"
  keyspace: "new_ks"
  username: "root"
  password: "password"

migration:
  batch_size: 1000        # 每批处理的记录数
  workers: 4              # 并发工作线程数
  rate_limit: 5000        # 每秒处理的记录数限制
  timeout: 30             # 连接超时时间（秒）
  checkpoint_dir: "./checkpoints"  # 断点续传文件保存目录
  checkpoint_delay: 60    # 断点保存间隔（秒）
  log_file: "./migration.log"
  log_level: "info"