source:
  type: mysql
  hosts:
    - "localhost:3306"
  database: "source_db"
  username: "root"
  password: "password"
  tables:
    - name: "users"
      target_name: "users_new"
      column_transformations:
        - source_column: "name"
          expression: "UPPER(name)"
        - source_column: "price"
          expression: "price * 100"
        - source_column: "create_time"
          expression: "DATE_FORMAT(create_time, '%Y-%m-%d')"
    - name: "orders"
      column_transformations:
        - source_column: "status"
          expression: "CONCAT('Status: ', status)"

destination:
  hosts:
    - "localhost:27018"
  database: "new_db"
  keyspace: "new_ks"
  username: "root"
  password: "password"

migration:
  batch_size: 1000        # Number of records per batch
  workers: 4              # Number of concurrent worker threads
  rate_limit: 10000       # Rate limit (records per second)
  timeout: 30             # Connection timeout (seconds)
  checkpoint_dir: "./data/checkpoints"  # Directory for checkpoint files (default)
  log_file: "./data/logs/migration.log"  # Log file path (default)
  log_level: "info"
  progress_interval: 5    # Progress report interval (seconds)
  language: "zh"         # Language setting: "zh" for Chinese, "en" for English